CREATE TABLE [dbo].[Selection] (
    [SelectionId]        INT IDENTITY (1, 1) NOT NULL,
    [SelectionForRaceId] INT NOT NULL,
    [PlayerId]           INT NOT NULL,
    [Driver1Id]          INT NULL,
    [Driver2Id]          INT NULL,
    [Driver3Id]          INT NULL,
    [Driver4Id]          INT NULL,
    [Constructor1Id]     INT NULL,
    [Constructor2Id]     INT NULL,
    [Engine1Id]          INT NULL,
    [Engine2Id]          INT NULL,
    [Answer1Id]          INT NULL,
    [Answer2Id]          INT NULL,
    [Answer3Id]          INT NULL,
    CONSTRAINT [PK_Selection_Id] PRIMARY KEY CLUSTERED ([SelectionId] ASC),
    CONSTRAINT [FK_PlayerRaceAnswer_Player] FOREIGN KEY ([PlayerId]) REFERENCES [dbo].[Player] ([PlayerId]),
    CONSTRAINT [FK_Selection_Answer1] FOREIGN KEY ([Answer1Id]) REFERENCES [dbo].[Answer] ([AnswerId]),
    CONSTRAINT [FK_Selection_Answer2] FOREIGN KEY ([Answer2Id]) REFERENCES [dbo].[Answer] ([AnswerId]),
    CONSTRAINT [FK_Selection_Answer3] FOREIGN KEY ([Answer3Id]) REFERENCES [dbo].[Answer] ([AnswerId]),
    CONSTRAINT [FK_Selection_Constructor1] FOREIGN KEY ([Constructor1Id]) REFERENCES [dbo].[Constructor] ([ConstructorId]),
    CONSTRAINT [FK_Selection_Constructor2] FOREIGN KEY ([Constructor2Id]) REFERENCES [dbo].[Constructor] ([ConstructorId]),
    CONSTRAINT [FK_Selection_Driver1] FOREIGN KEY ([Driver1Id]) REFERENCES [dbo].[Driver] ([DriverId]),
    CONSTRAINT [FK_Selection_Driver2] FOREIGN KEY ([Driver2Id]) REFERENCES [dbo].[Driver] ([DriverId]),
    CONSTRAINT [FK_Selection_Driver3] FOREIGN KEY ([Driver3Id]) REFERENCES [dbo].[Driver] ([DriverId]),
    CONSTRAINT [FK_Selection_Driver4] FOREIGN KEY ([Driver4Id]) REFERENCES [dbo].[Driver] ([DriverId]),
    CONSTRAINT [FK_Selection_Engine1] FOREIGN KEY ([Engine1Id]) REFERENCES [dbo].[Engine] ([EngineId]),
    CONSTRAINT [FK_Selection_Engine2] FOREIGN KEY ([Engine2Id]) REFERENCES [dbo].[Engine] ([EngineId]),
    CONSTRAINT [FK_Selection_Race] FOREIGN KEY ([SelectionForRaceId]) REFERENCES [dbo].[Race] ([RaceId])
);

